### ISSUE TITLE
False-positive: single module contains two items with the same name

### ISSUE THREAD

**Issue by SmolSir** [obi1kenobi/trustfall-rustdoc-adapter#171]
This bug was originally found during the verification of semver-crater results, thanks to the goblin crate's [`SectionHeader` item](https://docs.rs/goblin/0.6.1/src/goblin/elf/section_header.rs.html#385).

It is most likely caused by faulty or missing implementation of shadowing rules when re-exporting items from their parent module.

A short demonstration of the problem can be found [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6397c410214a808229061148f12f08e1).

**Comment by obi1kenobi** [comment]
In my efforts to produce a correct bugfix, I have created some truly horrifying Rust programs.

Check this out for example:
```rust
// This crate exports:
// - `Foo` only as itself
// - `inner::Foo` also as `inner::nested::Foo`.
//
// `inner`'s glob import is a no-op, and so is the top-level glob import of `inner::nested::*`.

pub use inner::nested::*;

pub struct Foo;

pub mod inner {
    pub use super::*;

    pub struct Foo;

    pub mod nested {
        pub use super::*;
    }
}
```
