### ISSUE TITLE
Expose `object_safe` property on `type Trait`

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/trustfall-rustdoc-adapter#320]
Rustdoc as of format version 28 shows whether traits are object-safe or not: https://docs.rs/rustdoc-types/latest/rustdoc_types/struct.Trait.html#structfield.is_object_safe

We want to expose a new `object_safe: Boolean!` field on `type Trait` so we can query this information in cargo-semver-checks lints.

**Comment by devanbenz** [comment]
@obi1kenobi This is WeblWabl from the timclicks discord - we had a brief discussion about OSS contribs :D I think I'm going to take on this issue & https://github.com/obi1kenobi/cargo-semver-checks/issues/635 since they are dependencies.

**Comment by obi1kenobi** [comment]
Nice! Look at how `type Trait` implements its `unsafe` property, you can use its implementation as a guide since it should be quite analogous.

**Comment by devanbenz** [comment]
@obi1kenobi Can I get permission to push to the github repository? I don't think I have read rights 🤔

**Comment by obi1kenobi** [comment]
Could you try forking the repo and opening a PR that way? The publishing
config is a bit sensitive here so I'd rather not mess with the permissions
if it's possible to avoid it right now.

**Comment by devanbenz** [comment]
We could probably link this commit to the issue and close it out now :D https://github.com/obi1kenobi/trustfall-rustdoc-adapter/pull/323

**Comment by obi1kenobi** [comment]
Nice! Resolved in #323 and published in v28.0.2.
